<?php

namespace Database\Seeders;

use App\Models\EmailTemplate;
use Illuminate\Database\Seeder;

/**
 * M7 · Seed idempotente de plantillas de correo.
 * Rellena la tabla con el contenido actual hard-coded de cada notif/mail.
 * Marian luego puede editar cada una desde el admin.
 */
class EmailTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $tpls = [
            [
                'key' => 'bienvenida_talento',
                'description' => 'Bienvenida al coach al registrarse.',
                'subject' => 'Bienvenido a Kinvoo, {{name}}',
                'greeting' => '¡Hola {{name}}!',
                'body' => "Nos alegra tenerte en Kinvoo. En cuanto completes tu perfil los estudios podrán encontrarte.\n\nComparte tu experiencia, disciplinas y disponibilidad — mientras más completo, más oportunidades verás.",
                'action_label' => 'Completar mi perfil',
                'action_url_hint' => 'route:professional.profile.edit',
                'outro' => 'Cualquier duda, escríbenos a hola@gokinvoo.com.',
                'placeholders_hint' => ['name'],
            ],
            [
                'key' => 'bienvenida_estudio',
                'description' => 'Bienvenida al estudio al registrarse.',
                'subject' => 'Bienvenido a Kinvoo, {{name}}',
                'greeting' => '¡Hola {{name}}!',
                'body' => "Gracias por elegir Kinvoo para tu estudio. Completa el perfil de tu empresa para poder publicar oportunidades y encontrar talento.",
                'action_label' => 'Completar mi empresa',
                'action_url_hint' => 'route:company.profile.edit',
                'outro' => 'Cualquier duda, escríbenos a hola@gokinvoo.com.',
                'placeholders_hint' => ['name'],
            ],
            [
                'key' => 'invitacion_equipo',
                'description' => 'Al coach cuando un estudio lo invita a su equipo.',
                'subject' => 'Kinvoo · {{estudio}} te invita a su equipo',
                'greeting' => 'Hola {{coach}},',
                'body' => "**{{estudio}}** quiere sumarte a su equipo en Kinvoo.\n\nAl aceptar, su cuidado empieza a sumar en tu perfil (telemedicina, fisio, contenido, etc. según el plan del estudio).",
                'action_label' => 'Ver invitación',
                'action_url_hint' => 'route:notifications.index',
                'outro' => 'Si no fue una invitación esperada, simplemente recházala desde la campanita.',
                'placeholders_hint' => ['coach', 'estudio'],
            ],
            [
                'key' => 'respuesta_equipo_aceptada',
                'description' => 'Al estudio cuando el coach ACEPTA la invitación al equipo.',
                'subject' => 'Kinvoo · {{coach}} aceptó tu invitación',
                'greeting' => 'Hola {{estudio}},',
                'body' => "**{{coach}}** aceptó formar parte de tu equipo en Kinvoo.\n\nA partir de ahora, su cuidado (consultas, fisio, charlas, etc.) suma en tu Panel de bienestar.",
                'action_label' => 'Ver mi equipo',
                'action_url_hint' => 'route:equipo.index',
                'outro' => 'Gracias por seguir cuidando a tu equipo con Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio'],
            ],
            [
                'key' => 'respuesta_equipo_rechazada',
                'description' => 'Al estudio cuando el coach RECHAZA la invitación al equipo.',
                'subject' => 'Kinvoo · {{coach}} declinó tu invitación',
                'greeting' => 'Hola {{estudio}},',
                'body' => "**{{coach}}** declinó por ahora tu invitación.\n\nEs normal — puedes invitar a otros profesionales cuando quieras.",
                'action_label' => 'Ver mi equipo',
                'action_url_hint' => 'route:equipo.index',
                'outro' => 'Gracias por seguir cuidando a tu equipo con Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio'],
            ],
            [
                'key' => 'postulacion_seen',
                'description' => 'Al coach cuando el estudio VE su postulación.',
                'subject' => 'Kinvoo · Tu postulación fue vista — {{oferta}}',
                'greeting' => 'Hola {{coach}},',
                'body' => "{{estudio}} revisó tu postulación. Si le interesa avanzar, te contactará pronto.\n\n**Oferta:** {{oferta}}",
                'action_label' => 'Ver mis postulaciones',
                'action_url_hint' => 'route:ofertas.mis-postulaciones',
                'outro' => 'Recibes este aviso porque postulaste a una oferta en Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio', 'oferta'],
            ],
            [
                'key' => 'postulacion_in_contact',
                'description' => 'Al coach cuando el estudio quiere contactarlo.',
                'subject' => 'Kinvoo · El estudio quiere contactarte — {{oferta}}',
                'greeting' => 'Hola {{coach}},',
                'body' => "{{estudio}} quiere entrar en contacto contigo respecto a esta postulación.\n\n**Oferta:** {{oferta}}",
                'action_label' => 'Ver mis postulaciones',
                'action_url_hint' => 'route:ofertas.mis-postulaciones',
                'outro' => 'Recibes este aviso porque postulaste a una oferta en Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio', 'oferta'],
            ],
            [
                'key' => 'postulacion_accepted',
                'description' => 'Al coach cuando el estudio ACEPTA su postulación.',
                'subject' => 'Kinvoo · ¡Postulación aceptada! — {{oferta}}',
                'greeting' => 'Hola {{coach}},',
                'body' => "¡Excelente noticia! {{estudio}} aceptó tu postulación y se pondrá en contacto contigo.\n\n**Oferta:** {{oferta}}",
                'action_label' => 'Ver mis postulaciones',
                'action_url_hint' => 'route:ofertas.mis-postulaciones',
                'outro' => 'Recibes este aviso porque postulaste a una oferta en Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio', 'oferta'],
            ],
            [
                'key' => 'postulacion_rejected',
                'description' => 'Al coach cuando el estudio RECHAZA su postulación.',
                'subject' => 'Kinvoo · Actualización de tu postulación — {{oferta}}',
                'greeting' => 'Hola {{coach}},',
                'body' => "{{estudio}} decidió no avanzar con tu postulación en esta ocasión. Sigue postulando — cada intento cuenta.\n\n**Oferta:** {{oferta}}",
                'action_label' => 'Ver mis postulaciones',
                'action_url_hint' => 'route:ofertas.mis-postulaciones',
                'outro' => 'Recibes este aviso porque postulaste a una oferta en Kinvoo.',
                'placeholders_hint' => ['coach', 'estudio', 'oferta'],
            ],
            [
                'key' => 'respaldo_nuevo_admin',
                'description' => 'Al admin (Kinvoo) cuando un coach solicita telemedicina o fisio.',
                'subject' => 'Kinvoo · Nuevo Respaldo pendiente ({{tipo}}) — {{coach}}',
                'greeting' => 'Hola equipo Kinvoo,',
                'body' => "{{coach}} pidió una sesión de **{{tipo}}**.\n\n**Prefiere:** {{preferred_slot}}\n**Nota:** {{note}}",
                'action_label' => 'Agendar en el panel',
                'action_url_hint' => '/admin/benefit-requests',
                'outro' => 'Al confirmar la fecha, el coach recibirá el aviso automáticamente.',
                'placeholders_hint' => ['coach', 'tipo', 'preferred_slot', 'note'],
            ],
            [
                'key' => 'respaldo_agendado_coach',
                'description' => 'Al coach cuando el admin agenda su sesión.',
                'subject' => 'Kinvoo · Tu sesión de {{tipo}} está agendada',
                'greeting' => 'Hola {{coach}},',
                'body' => "Tu solicitud de **{{tipo}}** ya fue agendada por Kinvoo.\n\n**Cuándo:** {{cuando}}\n**Nota Kinvoo:** {{admin_note}}",
                'action_label' => 'Ver detalle',
                'action_url_hint' => 'route:respaldo.index',
                'outro' => 'Si necesitas reprogramar, respóndenos a este correo.',
                'placeholders_hint' => ['coach', 'tipo', 'cuando', 'admin_note'],
            ],
            [
                'key' => 'cuenta_aprobada',
                'description' => 'Al coach cuando el admin aprueba su cuenta.',
                'subject' => 'Kinvoo · ¡Tu cuenta fue aprobada!',
                'greeting' => 'Hola {{coach}},',
                'body' => 'Tu cuenta ya está activa en Kinvoo. Ya puedes completar tu perfil, subir tu foto y publicarlo para que los estudios te encuentren.',
                'action_label' => 'Ir a mi panel',
                'action_url_hint' => 'route:dashboard',
                'outro' => '¡Bienvenido a la red profesional del fitness!',
                'placeholders_hint' => ['coach'],
            ],
            [
                'key' => 'cuenta_aprobada_contratante',
                'description' => 'Al estudio cuando el admin aprueba su cuenta.',
                'subject' => 'Kinvoo · ¡Tu cuenta de estudio fue aprobada!',
                'greeting' => 'Hola {{estudio}},',
                'body' => 'Tu cuenta ya está activa en Kinvoo. El siguiente paso es completar el perfil de tu estudio (nombre, ubicación, disciplinas, contacto). Cuando lo envíes, el equipo de Kinvoo lo revisará por segunda vez y quedará publicado en un máximo de 24 horas.',
                'action_label' => 'Completar perfil de empresa',
                'action_url_hint' => 'route:company.profile.edit',
                'outro' => 'Este segundo paso es rápido y nos asegura que los coaches confíen en tu marca desde el primer día.',
                'placeholders_hint' => ['estudio'],
            ],
            [
                'key' => 'cuenta_rechazada',
                'description' => 'A quien el admin rechaza su solicitud de registro.',
                'subject' => 'Kinvoo · Sobre tu solicitud de registro',
                'greeting' => 'Hola {{nombre}},',
                'body' => 'Después de revisar tu solicitud, no pudimos aprobarla en este momento.'."\n\n".'Si crees que fue un error o quieres conocer los pasos para reintentarlo, respóndenos a este correo o escríbenos a hola@gokinvoo.com. Con gusto te acompañamos.',
                'action_label' => null,
                'action_url_hint' => null,
                'outro' => 'Gracias por tu interés en Kinvoo.',
                'placeholders_hint' => ['nombre'],
            ],
            [
                'key' => 'perfil_empresa_aprobado',
                'description' => 'Al estudio cuando su perfil de empresa se publica.',
                'subject' => 'Kinvoo · Tu perfil de {{estudio}} ya está publicado',
                'greeting' => 'Hola {{estudio}},',
                'body' => 'Tu perfil de empresa acaba de aprobarse y ya está publicado en el directorio de Kinvoo. Los coaches pueden encontrarte y ya puedes empezar a buscar talento y contactarlos.',
                'action_label' => 'Buscar talento ahora',
                'action_url_hint' => 'route:talento.index',
                'outro' => 'Cualquier duda, aquí estamos: hola@gokinvoo.com',
                'placeholders_hint' => ['estudio'],
            ],
            [
                'key' => 'removido_equipo',
                'description' => 'Al coach cuando un estudio lo retira de su equipo.',
                'subject' => 'Kinvoo · Ya no formas parte del equipo de {{estudio}}',
                'greeting' => 'Hola {{coach}},',
                'body' => '**{{estudio}}** te retiró de su equipo en Kinvoo.'."\n\n".'Tu perfil sigue activo y puedes seguir aplicando a otras oportunidades. Los beneficios del estudio (telemedicina, fisio, contenido) dejan de acumularse desde hoy, pero conservas todo lo que ya recibiste.',
                'action_label' => 'Ver mis notificaciones',
                'action_url_hint' => 'route:notifications.index',
                'outro' => 'Si crees que fue un error, ponte en contacto con el estudio directamente.',
                'placeholders_hint' => ['coach', 'estudio'],
            ],
            [
                'key' => 'momento_rechazado',
                'description' => 'Al coach cuando el admin rechaza su momento del Wall.',
                'subject' => 'Kinvoo · Tu momento no se publicó',
                'greeting' => 'Hola,',
                'body' => 'El equipo de Kinvoo revisó tu momento en el Wall y no pudo aprobarlo.'."\n\n".'**Motivo:** {{motivo}}',
                'action_label' => 'Ver mis momentos',
                'action_url_hint' => 'route:wall.mis-momentos',
                'outro' => 'Puedes subir uno nuevo cuando quieras. Estamos aquí para lo que necesites.',
                'placeholders_hint' => ['motivo'],
            ],
            [
                'key' => 'nueva_postulacion',
                'description' => 'Al estudio cuando un coach postula a su oferta.',
                'subject' => 'Kinvoo · Nueva postulación a "{{oferta}}"',
                'greeting' => 'Hola {{estudio}},',
                'body' => '**{{nombre}}** acaba de postular a tu vacante "{{oferta}}" en Kinvoo. Revisa su perfil, carta de presentación y ponte en contacto directamente.',
                'action_label' => 'Ver postulaciones',
                'action_url_hint' => 'route:ofertas.mis-ofertas',
                'outro' => 'Consejo: los coaches valoran una respuesta rápida — les da confianza sobre tu estudio.',
                'placeholders_hint' => ['nombre', 'oferta'],
            ],
            [
                'key' => 'pulso_respondido',
                'description' => 'Al estudio cuando alguien de su equipo contesta el Pulso.',
                'subject' => 'Kinvoo · Nueva respuesta al Pulso de tu equipo',
                'greeting' => 'Hola,',
                'body' => 'Alguien de tu equipo contestó la encuesta de Pulso Kinvoo esta semana.'."\n\n".'Las respuestas son anónimas — no vas a saber quién contestó, pero sí puedes ver el score general y el comentario destacado. Es la mejor forma de tomar el pulso al bienestar de tu equipo.',
                'action_label' => 'Ver Pulso Kinvoo',
                'action_url_hint' => 'route:pulso.estudio',
                'outro' => 'Tip: revisa el Pulso una vez a la semana para captar tendencias.',
                'placeholders_hint' => [],
            ],
            [
                'key' => 'respaldo_cancelado',
                'description' => 'Al coach cuando el admin cancela su sesión de respaldo.',
                'subject' => 'Kinvoo · Tu sesión de {{tipo}} fue cancelada',
                'greeting' => 'Hola {{coach}},',
                'body' => 'Tu sesión de **{{tipo}}** fue cancelada por el equipo de Kinvoo.'."\n\n".'**Importante:** no te presentes a la hora original — la sesión ya no está en pie. Puedes solicitar una nueva desde tu panel o escribirnos a hola@gokinvoo.com para reagendar.',
                'action_label' => 'Ir a mi respaldo',
                'action_url_hint' => 'route:respaldo.index',
                'outro' => 'Lamentamos las molestias.',
                'placeholders_hint' => ['coach', 'tipo'],
            ],
            [
                'key' => 'profesional_interesado',
                'description' => 'Al admin cuando un coach marca "Me interesa, conéctame" en un contacto.',
                'subject' => 'Conexión pendiente en Kinvoo · {{profesional}} quiere conectar con {{estudio}}',
                'greeting' => 'Hola equipo Kinvoo,',
                'body' => '{{profesional}} marcó "Me interesa, conéctame" en la bandeja de contactos.'."\n\n".'Quiere que hagamos el puente con **{{estudio}}**.'."\n\n".'Mensaje original del estudio:'."\n\n".'> {{mensaje}}',
                'action_label' => 'Ver en el panel',
                'action_url_hint' => 'route:filament.admin.resources.contacts.index',
                'outro' => 'Recuerda cerrar la conexión y avisar a ambas partes por su canal habitual.',
                'placeholders_hint' => ['profesional', 'estudio', 'mensaje'],
            ],
            [
                'key' => 'aviso_cobro_exitoso',
                'description' => 'Al usuario cuando MercadoPago cobra su membresía correctamente.',
                'subject' => 'Recibimos tu pago — Kinvoo',
                'greeting' => 'Hola {{nombre}},',
                'body' => 'Recibimos correctamente el cobro de **{{plan}}**. Tu membresía queda activa. ¡Gracias por seguir siendo parte de Kinvoo!',
                'action_label' => 'Ver mi membresía',
                'action_url_hint' => 'route:membresias.index',
                'outro' => 'Guarda este correo como comprobante.',
                'placeholders_hint' => ['nombre', 'plan'],
            ],
            [
                'key' => 'aviso_cobro_fallido',
                'description' => 'Al usuario cuando un cobro de renovación falla.',
                'subject' => 'Tu cobro no se pudo completar — Kinvoo',
                'greeting' => 'Hola {{nombre}},',
                'body' => 'No pudimos procesar el cobro de **{{plan}}**. Revisa tu método de pago desde tu panel; volveremos a intentarlo pronto.',
                'action_label' => 'Actualizar mi pago',
                'action_url_hint' => 'route:membresias.index',
                'outro' => 'Si necesitas ayuda, escríbenos.',
                'placeholders_hint' => ['nombre', 'plan'],
            ],
            [
                'key' => 'aviso_cobro_proximo',
                'description' => 'Recordatorio 7 días antes del cobro de renovación.',
                'subject' => 'Tu renovación de Kinvoo se acerca',
                'greeting' => 'Hola {{nombre}},',
                'body' => 'La renovación de **{{plan}}** se hará el **{{fecha}}**. Verifica que tu método de pago esté vigente para que no se interrumpa tu acceso.',
                'action_label' => 'Ver mi membresía',
                'action_url_hint' => 'route:membresias.index',
                'outro' => '¿No quieres renovar? Puedes cancelar desde tu panel.',
                'placeholders_hint' => ['nombre', 'plan', 'fecha'],
            ],
            [
                'key' => 'aviso_vencimiento_membresia',
                'description' => 'Al usuario cuando su membresía se venció.',
                'subject' => 'Tu membresía Kinvoo venció',
                'greeting' => 'Hola {{nombre}},',
                'body' => 'Tu membresía en Kinvoo venció. Los beneficios de tu plan quedan pausados hasta que renueves.'."\n\n".'Puedes renovar en un clic desde tu panel.',
                'action_label' => 'Renovar mi membresía',
                'action_url_hint' => 'route:membresias.index',
                'outro' => 'Tu perfil y datos siguen intactos — puedes retomar cuando quieras.',
                'placeholders_hint' => ['nombre'],
            ],
            [
                'key' => 'nuevo_contacto',
                'description' => 'Al owner cuando un estudio contacta a un coach desde la ficha pública.',
                'subject' => 'Nuevo contacto en Kinvoo — {{estudio}}',
                'greeting' => 'Hola equipo Kinvoo,',
                'body' => '**{{estudio}}** contactó a **{{profesional}}** en Kinvoo.'."\n\n".'Mensaje:'."\n\n".'> {{mensaje}}',
                'action_label' => 'Ver en el panel',
                'action_url_hint' => 'route:filament.admin.resources.contacts.index',
                'outro' => 'Revísalo cuanto antes para dar seguimiento.',
                'placeholders_hint' => ['estudio', 'profesional', 'mensaje'],
            ],
            [
                'key' => 'invitacion_sesion',
                'description' => 'Al invitado cuando el admin le manda una invitación a una sesión en vivo.',
                'subject' => 'Kinvoo · Te invitamos a: {{titulo}}',
                'greeting' => '¡Hola {{nombre}}!',
                'body' => 'Te invitamos a nuestra próxima sesión en Kinvoo:'."\n\n".'**{{titulo}}**'."\n".'🗓 {{fecha}}',
                'action_label' => null, // los botones RSVP los pinta la vista
                'action_url_hint' => null,
                'outro' => '¿Podrás asistir? Confírmanos para reservarte el cupo:',
                'placeholders_hint' => ['nombre', 'titulo', 'fecha'],
            ],
        ];

        // firstOrCreate (NO updateOrCreate): así un re-seed en cada deploy NO
        // pisa las ediciones que el admin hizo desde el panel. Solo crea las
        // que falten.
        foreach ($tpls as $t) {
            EmailTemplate::firstOrCreate(['key' => $t['key']], $t);
        }
    }
}
